# Generated by Django 4.2.7 on 2026-01-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
